### ISSUE TITLE
Restriction for data to be JSON

### ISSUE THREAD

**Issue by Tabrizian** [bambil/Haho#1]
Do you think it's necessary to put constraint on message to be JSON?

**Comment by 1995parham** [comment]
Yes, I think we can add some restriction using [joi](https://github.com/hapijs/joi).

**Comment by 1995parham** [comment]
Joi validation was added for subscribe function, what do you think? :thinking:

**Comment by Tabrizian** [comment]
Perfect bro, what about receiving a third option, a validator, as an input? 
```javascript
haho.subscribe(
    [
        {
            subscribe: 'hello/world',
            validator: Joi.number().integer().min(1900).max(2013),
            handler: (message) => {

            }
        }

    ]
)

```

**Comment by 1995parham** [comment]
Oooh, You talk about validating mqtt packets! this awesome, I will add it right now.

**Comment by 1995parham** [comment]
Subscription validators were added, 🕺

**Comment by 1995parham** [comment]
We are on milestone 😌
