### ISSUE TITLE
Support arrayish subscription 

### ISSUE THREAD

**Issue by Tabrizian** [bambil/Haho#3]
What's your idea, about adding a structure for supporting subscription like below:

```javascript

haho.subscribe([
    {
         topic: 'hello/world1',
         handler: handler1
    },
    {
         topic: 'hello/world2',
         handler: handler2
    }
])
```
/cc @1995parham

**Comment by 1995parham** [comment]
Yes, I think it's awesome, sorry for my delay, I will add this issue and validation issue today.

**Comment by Tabrizian** [comment]
ن بابا اين حرفا چيه 😂✌🏻

**Comment by 1995parham** [comment]
Done Bro 👍
